server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: secure-auth-system

  datasource:
    url: jdbc:postgresql://localhost:5432/secureauthdb
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:kgangadhar0807@gmail.com}
    password: ${MAIL_PASSWORD:mqkwzifqriwotktn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


jwt:
  secret: ${JWT_SECRET:uXJ2T8c5R9m7V4N0WQy6A1DkZsH8EJvP0fM3LrYbK2I=}
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 604800000

#for prod true
cookie:
  secure: false
  same-site: strict
  domain: ${COOKIE_DOMAIN:localhost}

# OTP Configuration
otp:
  expiration: 600000 # 10 minutes in milliseconds
  length: 6

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  max-refresh-tokens-per-user: 5
  require-email-verification: true